apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  containers:
  - name: writer
    image: busybox:1.36
    command:
      - sh
      - -c
    args: 
      - |
        while true; do
          date >> /data/output.txt
          sleep 5
        done
    volumeMounts:
      - name: shared-data
        mountPath: /data
  volumes:
    - name: shared-data
      emptyDir: {}