apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: store
spec:
  selector:
    matchLabels:
      app: nginx-store
  serviceName: database-store
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-store
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: store-volume
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: store-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
