apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
  labels:
    app.kubernetes.io/name: selector-app
spec:
  nodeSelector:
    environment: prod
  containers:
  - name: nginx-selector-app
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
