apiVersion: v1
kind: Pod
metadata:
  name: ordinary-pod
spec:
  tolerations:
    - key: workload
      operator: Equal
      value: special
      effect: NoSchedule
  containers:
  - name: nginx-pod-without-toleration
    image: nginx:alpine
