apiVersion: v1
kind: Pod
metadata:
  name: probing-demo
  labels:
    app.kubernetes.io/name: probe-pod
spec:
  containers:
  - name: web

    image: nginx:alpine

    ports:
      - containerPort: 80

    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5

    volumeMounts:
      - name: test-pvc
        mountPath: /data

  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-pvc-demo