apiVersion: v1
kind: Pod
metadata:
  name: tolerable-pod
spec:
  nodeSelector:
    workload: ml
  tolerations:
    - key: dedicated
      operator: Equal
      value: ml
      effect: NoSchedule
  containers:
  - name: nginx
    image: nginx:alpine
